package model;

import model.base.BaseCourseselection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Courseselection extends BaseCourseselection<Courseselection> {
	public static final Courseselection dao = new Courseselection().dao();
}

