package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCourse<M extends BaseCourse<M>> extends Model<M> implements IBean {

	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}
	
	public java.lang.String getCid() {
		return getStr("cid");
	}
	
	public void setCname(java.lang.String cname) {
		set("cname", cname);
	}
	
	public java.lang.String getCname() {
		return getStr("cname");
	}
	
	public void setTeacher(java.lang.String teacher) {
		set("teacher", teacher);
	}
	
	public java.lang.String getTeacher() {
		return getStr("teacher");
	}
	
	public void setCapacity(java.lang.String capacity) {
		set("capacity", capacity);
	}
	
	public java.lang.String getCapacity() {
		return getStr("capacity");
	}
	
	public void setSelected(java.lang.String selected) {
		set("selected", selected);
	}
	
	public java.lang.String getSelected() {
		return getStr("selected");
	}
	
	public void setTimelength(java.lang.String timelength) {
		set("timelength", timelength);
	}
	
	public java.lang.String getTimelength() {
		return getStr("timelength");
	}
	
	public void setPlace(java.lang.String place) {
		set("place", place);
	}
	
	public java.lang.String getPlace() {
		return getStr("place");
	}
	
}

